// layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" className="h-full">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable}
          min-h-screen
          bg-[radial-gradient(900px_500px_at_15%_10%,#dcfce7_0%,transparent_60%),linear-gradient(#f7f6f2,#f7f6f2)]
          text-emerald-950
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
